/*CREATE TABLE USUARIO(
TAG_USUARIO VARCHAR2(20) NOT NULL PRIMARY KEY,
CONTRASENYA VARCHAR2(16) NOT NULL,
DOMICILIO VARCHAR2(25),
COD_POSTAL INTEGER,
EMAIL VARCHAR2(30),
FECH_NAC DATE,
NOMBRE VARCHAR2(30) NOT NULL,
APELLIDOS VARCHAR2(50) NOT NULL,
NUM_TARJETA INTEGER,
CHANGEDTS DATE
);
*/
/*CREATE TABLE GENERO(
ID INTEGER NOT NULL PRIMARY KEY,
TIPO VARCHAR2(16) NOT NULL,
CHANGEDTS DATE
);
*/
/*CREATE TABLE TARIFA(
ID INTEGER NOT NULL PRIMARY KEY,
PRECIO FLOAT NOT NULL,
CHANGEDTS DATE
);
*/
/*CREATE TABLE CONTENIDO(
ID INTEGER NOT NULL PRIMARY KEY,
TITULO VARCHAR2(30) NOT NULL,
DESCRIPCION VARCHAR2(80) NOT NULL,
URL_IMAGEN VARCHAR2(200),
ACTORES VARCHAR2(160),
PUNT_MEDIA FLOAT,
FECH_ESTRENO DATE,
DURACION FLOAT,
DIRECTOR VARCHAR2(35) NOT NULL,
CHANGEDTS DATE,
ID_GENERO INTEGER NOT NULL,
ID_TARIFA INTEGER NOT NULL,
CONSTRAINT FK_GENERO FOREIGN KEY (ID_GENERO) REFERENCES GENERO(ID),
CONSTRAINT FK_TARIFA FOREIGN KEY (ID_TARIFA) REFERENCES TARIFA(ID)
);
*/
/*CREATE TABLE CORTO(
ID_CONT INTEGER NOT NULL PRIMARY KEY
);*/
/*CREATE TABLE PELICULA(
ID_CONT INTEGER NOT NULL PRIMARY KEY,
DISPONIBLE_HASTA DATE
);*/
/*CREATE TABLE SERIE(
ID INTEGER NOT NULL PRIMARY KEY,
DISPONIBILIDAD DATE,
TITULO VARCHAR2(16) NOT NULL,
DESCRIPCION VARCHAR(80) NOT NULL
);*/
/*CREATE TABLE CAPITULO(
ID_CONT INTEGER NOT NULL PRIMARY KEY,
TEMPORADA INTEGER,
ID_SERIE NOT NULL,
CONSTRAINT FK_SERIE FOREIGN KEY (ID_SERIE) REFERENCES SERIE(ID)
);*/
/*CREATE TABLE CARRO_COMPRA(
ID INTEGER NOT NULL PRIMARY KEY,
CHANGEDTS DATE,
ID_USUARIO VARCHAR2(20) NOT NULL,
CONSTRAINT FK_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(TAG_USUARIO)
);*/
/*CREATE TABLE VALORA(
ID_USUARIO VARCHAR2(20) NOT NULL,
ID_CONTENIDO INTEGER NOT NULL,
PUNTOS FLOAT,
PRIMARY KEY (ID_USUARIO,ID_CONTENIDO),
CONSTRAINT FK_USUARIOVALORA FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(TAG_USUARIO),
CONSTRAINT FK_CONTENIDOVALORA FOREIGN KEY (ID_CONTENIDO) REFERENCES CONTENIDO(ID)
);*/
/*CREATE TABLE FACTURA(
NUMERO INTEGER NOT NULL PRIMARY KEY,
FECHA DATE,
IMP_BASE FLOAT,
IMP_IVA FLOAT,
CHANGEDTS DATE,
ID_USUARIO VARCHAR2(20) NOT NULL,
CONSTRAINT FK_USUARIOFACTURA FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(TAG_USUARIO)
);*/
/*CREATE TABLE LINEA_FACTURA(
ID INTEGER NOT NULL PRIMARY KEY,
CHANGEDTS DATE,
ID_CARRO INTEGER NOT NULL,
NUM_FACTURA INTEGER NOT NULL,
CONSTRAINT FK_CARRO FOREIGN KEY (ID_CARRO) REFERENCES CARRO_COMPRA(ID),
CONSTRAINT FK_NUMFACTURA FOREIGN KEY (NUM_FACTURA) REFERENCES FACTURA(NUMERO)
);*/
/*CREATE TABLE ARTICULOS_FACTURAR(
ID_LINEA INTEGER NOT NULL,
ID_CONTENIDO INTEGER NOT NULL,
PRIMARY KEY (ID_LINEA,ID_CONTENIDO),
CONSTRAINT FK_LINEA FOREIGN KEY (ID_LINEA) REFERENCES LINEA_FACTURA(ID),
CONSTRAINT FK_CONTENIDOFACTURAR FOREIGN KEY (ID_CONTENIDO) REFERENCES CONTENIDO(ID)
);*/
/*CREATE TABLE GESTIONA(
ID_USUARIO VARCHAR2(20) NOT NULL,
ID_CONTENIDO INTEGER NOT NULL,
PRIMARY KEY(ID_USUARIO,ID_CONTENIDO),
CONSTRAINT FK_USUARIOGESTOR FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(TAG_USUARIO),
CONSTRAINT FK_CONTENIDOGESTION FOREIGN KEY (ID_CONTENIDO) REFERENCES CONTENIDO(ID)
);*
/*CREATE TABLE ALQUILA(
ID_USUARIO VARCHAR2(20) NOT NULL,
ID_CONTENIDO INTEGER NOT NULL,
PRIMARY KEY (ID_USUARIO, ID_CONTENIDO),
CONSTRAINT FK_USUARIOALQUILA FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(TAG_USUARIO),
CONSTRAINT FK_CONTENIDOALQUILADO FOREIGN KEY (ID_CONTENIDO) REFERENCES CONTENIDO(ID)
);*/